#!/usr/bin/env python
"""Usage: render <font>

Render the text from stdin using <font> as a PNG on stdout.
<font> must be a pango font description[1]
[1]: https://docs.gtk.org/Pango/type_func.FontDescription.from_string.html"""

import os
import sys
from typing import BinaryIO

import gi

gi.require_version("cairo", "1.0")
gi.require_version("Pango", "1.0")
gi.require_version("PangoCairo", "1.0")

import cairo
from gi.repository import Pango, PangoCairo


width = 1800
height = 16_000

def render(text: str, desc: str, file: BinaryIO):
    font = Pango.FontDescription.from_string(desc)
    surface = cairo.ImageSurface(cairo.Format.ARGB32, width, height)
    context = cairo.Context(surface)
    context.set_source_rgb(1, 1, 1)
    context.paint()
    context.set_source_rgb(0, 0, 0)
    layout = PangoCairo.create_layout(context)
    layout.set_font_description(font)
    layout.set_text(text)
    PangoCairo.show_layout(context, layout)
    surface.write_to_png(file)


if __name__ == "__main__":
    if len(sys.argv) != 2:
        print(__doc__)
        sys.exit(os.EX_USAGE)
    desc = sys.argv[1]
    text = sys.stdin.read()
    render(text, desc, sys.stdout.buffer)
